import type { Metadata } from "next";

import FontProvider from "@/lib/FontProvider";

import "@/lib/styles/bootstrap.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<FontProvider />
			<body>{children}</body>
		</html>
	);
}
